### PR TITLE
updated StoryRouter to use recommended data router

### PR DESCRIPTION
**Pull request by hugofelp**
Attempt to fix issues related to new data routers: https://github.com/JesusTheHun/storybook-addon-react-router-v6/issues/19

### CODE REVIEW

**Comment by afn** [comment]
@JesusTheHun Can you merge this in? 🙏

**Comment by JesusTheHun** [comment]
@afn No. This PR breaks many things and does not port the current features to the new router. I'm working on a proper implementation.

**Comment by afn** [comment]
Ah okay. Meanwhile if anyone wants to use the forked package:
```
yarn add -D storybook-addon-react-router-v6@cygnuseducation/storybook-addon-react-router-v6
```

(I had to add a prepare script to allow the package to be installed from git — see 0130cd4455d0c2c714f1b20e0b31022c2fb9254f)

**Comment by JesusTheHun** [comment]
I'm closing this as my implementation is now complete.

**Pull request closed without merging**
